[package]
name = "astar-rust"
version = "0.1.0"
authors = ["Pepijn Dragt <pepijn.dragt@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.6.1"
hashbrown = "0.1.7"
wasm-bindgen = "0.2.29"

[profile.dev]
opt-level = 3

[dev-dependencies]
wasm-bindgen-cli = "0.2.29"